sudo: required
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.18.0
branches:
  only:
  - master
  - develop
  - "/^(release).*$/"
  - "/^(hotfix).*$/"
  - "/^(feature).*$/"
language: node_js
node_js:
- '9'
before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
- yarn --cwd services/client install
script:
- yarn --cwd services/client build
- docker build -t app services/users/
deploy:
- provider: script
  script: docker tag app registry.heroku.com/$HEROKU_APP_NAME_PROD/web; docker push
    app; docker push registry.heroku.com/$HEROKU_APP_NAME_PROD/web; heroku container:release
    web --app $HEROKU_APP_NAME_PROD
  on:
    branch: master
- provider: script
  script: 
    docker tag app registry.heroku.com/$HEROKU_APP_NAME_STAGE/web;
    docker push registry.heroku.com/$HEROKU_APP_NAME_STAGE/web;
    heroku container:release web --app $HEROKU_APP_NAME_STAGE
  on:
    all_branches: true
notifications:
  slack:
    secure: hnJ9CHWU+aoeIRl4tItLnWXaoM51R8c9J9P4k/FELcqaFLZIqzpUbl04+0i13vRDnF/mT8cThlI3vkivyYt+GMnGEyrOP3xLsHRovMASgqZC1BOPc/BLMgW8sHNRhJ4eQQD1DVTp6rEdAiGE3sc/FmoUx8xIMvDjUXevAmH5ZhMKNXrDCiyoRbpatkIGXs3iyPcIQs4vNljKtaVbXQlPMcQhrkXv9ZW/ejVjx7msYcTSDFknIb+5L+ScHS4bxdO6WO9reTfzfWj0JY4f1aWUxSjl3Yq+LpvGpc17f+ik8U5antuLY31bDV1z20y/+jY3CviVYwdJCg/BzqCGcTQPG/oBQiX0OVs+Lxu47qYDKec8zIBS0sA4JdEvL0xhyWkWQYU9w+2RJEIepe6wGLXRvTffTBCjhtTJp7buv3HnKyhWBiGB/A/vpDpSu5b/vupYTgUUsPOj2jHaAcFoXvDVN0mvaWCXymmRKk2M3fY7UljZVDep+qhd/oBAdnRdSmv7iy2EISk05pMXnzfJMiT/ERoAa16mnHUtGsDDzA9cZLfjNDVPgG/uCvXPJKYMhzqszeRrsTVwHveF7TpILTxf9nd0M0SiIIXLbm/x7WclxpIcLK3soSUEVZMUexnhocl9GNb93lmmL0cuiaaJk2f3woL6WxNOwa3NPTeXFsZ64hA=
  email: false
